stages:
  - npm_install
  - lint
  - test
  - audit
  - build

# Cache modules in between jobs
cache:
  key: "${CI_COMMIT_REF_SLUG}_${CI_JOB_NAME}"
  paths:
  - .npm/

# Bases
.base: &base
  image: "node:lts"
  before_script:
    # Install deps
    - npm ci --cache .npm --prefer-offline

.lint: &lint
  <<: *base
  stage: lint
  script:
    - npm run lint

.tests: &tests
  <<: *base
  stage: test
  script:
    - npm run test

.audit: &audit
  <<: *base
  stage: audit
  allow_failure: true
  script:
    - npm audit

.build: &build
  <<: *base
  stage: build
  script:
    - npm run build

.install: &install
  stage: npm_install
  image: "node:lts"
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules
      - .npm

##############
# Install and cache artifacts

npm_install:
  <<: *install

npm_install:erbium:
  <<: *install
  image: "node:erbium"

npm_install:dubnium:
  <<: *install
  image: "node:dubnium"

##############
# Lint

lint:
  <<: *lint
  dependencies:
    - npm_install

lint:erbium:
  <<: *lint
  image: "node:erbium"
  dependencies:
    - "npm_install:erbium"

lint:dubnium:
  <<: *lint
  image: "node:dubnium"
  dependencies:
    - "npm_install:dubnium"

##############
# Unit tests

unit_test:
  <<: *tests

unit_test:erbium:
  <<: *tests
  image: "node:erbium"

unit_test:dubnium:
  <<: *tests
  image: "node:dubnium"

##############
# Audits

audit:
  <<: *audit
  dependencies:
    - npm_install

audit:erbium:
  <<: *audit
  image: "node:erbium"
  dependencies:
    - "npm_install:erbium"

audit:dubnium:
  <<: *audit
  image: "node:dubnium"
  dependencies:
    - "npm_install:dubnium"

##############
# Audits

build:
  <<: *build
  dependencies:
    - npm_install

build:erbium:
  <<: *build
  image: "node:erbium"
  dependencies:
    - "npm_install:erbium"

build:dubnium:
  <<: *build
  image: "node:dubnium"
  dependencies:
    - "npm_install:dubnium"
